# Generated by Django 3.0.4 on 2021-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
